// Rendering helpers for the corpus report: a human-readable stdout table, a
// Markdown report, and the JSON report. Shared by `cli.ts` and `corpus.test.ts`
// so the table the test prints matches the one the CLI prints.

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { CorpusReport } from './corpus-runner.js';

const MODULE_DIR = dirname(fileURLToPath(import.meta.url));
const PACKAGE_DIR = resolve(MODULE_DIR, '..');
const REPORT_JSON_PATH = resolve(PACKAGE_DIR, 'report.json');
const REPORT_MD_PATH = resolve(PACKAGE_DIR, 'report.md');

function pad(value: string, width: number): string {
  return value.length >= width ? value : value + ' '.repeat(width - value.length);
}

function fmtConfidence(confidence: number | undefined): string {
  return confidence === undefined ? '—' : confidence.toFixed(3);
}

/** Build the per-fixture table as an array of text lines (no trailing newline). */
export function renderTable(report: CorpusReport): string[] {
  const lines: string[] = [];
  const header = [
    pad('fixture', 28),
    pad('expected', 14),
    pad('detected', 14),
    pad('match', 6),
    pad('conf', 7),
    pad('hardPASS', 9),
  ].join(' ');
  lines.push(header);
  lines.push('-'.repeat(header.length));

  for (const fx of report.fixtures) {
    lines.push(
      [
        pad(fx.file, 28),
        pad(fx.expectedPageType, 14),
        pad(fx.detectedPageType ?? '<none>', 14),
        pad(fx.pageTypeMatch ? 'yes' : 'NO', 6),
        pad(fmtConfidence(fx.confidence), 7),
        pad(`${fx.hardPassCount}/${fx.comboCount}`, 9),
      ].join(' '),
    );
  }
  return lines;
}

/** Build the one-line summary string. */
export function renderSummary(report: CorpusReport): string {
  const accuracyPct = (report.pageTypeAccuracy * 100).toFixed(1);
  const floorPct = (report.pageTypeAccuracyFloor * 100).toFixed(1);
  return [
    `fixtures=${report.generatedFromFixtureCount}`,
    `combos/fixture=${report.comboCount}`,
    `page-type accuracy=${accuracyPct}% (floor ${floorPct}%)`,
    `hard failures=${report.hardFailures.length}`,
    `security failures(all levels)=${report.securityFailureCount}`,
    `page-type mismatches=${report.pageTypeMismatches.length}`,
    `soft warnings=${report.softFailures.length}`,
    `verdict=${report.ok ? 'PASS' : 'FAIL'}`,
  ].join(' | ');
}

/** Print the full table + summary + failure detail to stdout. */
export function printReport(report: CorpusReport): void {
  for (const line of renderTable(report)) console.log(line);
  console.log('');
  console.log(renderSummary(report));

  if (report.pageTypeMismatches.length > 0) {
    console.log('');
    console.log('page-type mismatches (soft, non-fatal):');
    for (const m of report.pageTypeMismatches) {
      console.log(`  - ${m.file}: expected ${m.expected}, detected ${m.detected ?? '<none>'}`);
    }
  }

  if (report.hardFailures.length > 0) {
    console.log('');
    console.log('HARD FAILURES (these fail the run):');
    for (const f of report.hardFailures) {
      console.log(`  - [${f.combo}] ${f.fixture} :: ${f.assertion} — ${f.detail}`);
    }
  }
}

/** Render the Markdown report body. */
export function renderMarkdown(report: CorpusReport): string {
  const accuracyPct = (report.pageTypeAccuracy * 100).toFixed(1);
  const floorPct = (report.pageTypeAccuracyFloor * 100).toFixed(1);
  const lines: string[] = [];

  lines.push('# htmlwasher corpus report');
  lines.push('');
  lines.push('> Generated by `@htmlwasher/wash-corpus-tester` (offline, deterministic).');
  lines.push('');
  lines.push(`_${report.attribution}_`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`- Fixtures: **${report.generatedFromFixtureCount}**`);
  lines.push(`- Combos per fixture: **${report.comboCount}**`);
  lines.push(`- Page-type accuracy: **${accuracyPct}%** (floor ${floorPct}%)`);
  lines.push(`- Hard-assertion failures: **${report.hardFailures.length}**`);
  lines.push(
    `- Security-assertion failures (all levels, incl. \`correct\`): **${report.securityFailureCount}**`,
  );
  lines.push(`- Page-type mismatches (soft): **${report.pageTypeMismatches.length}**`);
  lines.push(`- Soft warnings total: **${report.softFailures.length}**`);
  lines.push(`- Verdict: **${report.ok ? 'PASS' : 'FAIL'}**`);
  lines.push('');

  lines.push('## Per-fixture results');
  lines.push('');
  lines.push('| fixture | expected | detected | match | confidence | hard PASS |');
  lines.push('| --- | --- | --- | --- | --- | --- |');
  for (const fx of report.fixtures) {
    lines.push(
      `| ${fx.file} | ${fx.expectedPageType} | ${fx.detectedPageType ?? '—'} | ${
        fx.pageTypeMatch ? 'yes' : 'NO'
      } | ${fmtConfidence(fx.confidence)} | ${fx.hardPassCount}/${fx.comboCount} |`,
    );
  }
  lines.push('');

  if (report.pageTypeMismatches.length > 0) {
    lines.push('## Page-type mismatches (soft, non-fatal)');
    lines.push('');
    for (const m of report.pageTypeMismatches) {
      lines.push(
        `- \`${m.file}\`: expected \`${m.expected}\`, detected \`${m.detected ?? 'none'}\``,
      );
    }
    lines.push('');
  }

  const otherSoft = report.softFailures.filter((f) => f.assertion !== 'page-type-match');
  if (otherSoft.length > 0) {
    lines.push('## Soft warnings (documented, non-fatal)');
    lines.push('');
    lines.push(
      'Non-fatal soft assertions recorded for visibility. Security is a HARD assertion at every washing level (including `correct`) — the v2 washing floor is unconditional (context doc 09), so no security check is ever downgraded to a soft warning.',
    );
    lines.push('');
    for (const f of otherSoft) {
      lines.push(`- \`[${f.combo}] ${f.fixture}\` — **${f.assertion}**: ${f.detail}`);
    }
    lines.push('');
  }

  if (report.hardFailures.length > 0) {
    lines.push('## Hard failures');
    lines.push('');
    for (const f of report.hardFailures) {
      lines.push(`- \`[${f.combo}] ${f.fixture}\` — **${f.assertion}**: ${f.detail}`);
    }
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

/** Write `report.json` + `report.md` into the package directory. */
export function writeReports(report: CorpusReport): { jsonPath: string; mdPath: string } {
  writeFileSync(REPORT_JSON_PATH, `${JSON.stringify(report, null, 2)}\n`, 'utf8');
  writeFileSync(REPORT_MD_PATH, renderMarkdown(report), 'utf8');
  return { jsonPath: REPORT_JSON_PATH, mdPath: REPORT_MD_PATH };
}
