/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Extract the main content of an HTML document (async — runs on the libuv threadpool).
 *
 * # Errors
 * Rejects the promise with a JS `Error` on an invalid `pageType`/`focus` string or if
 * the classifier artifacts fail to load.
 */
export declare function extract(html: string, options?: ExtractOptions | undefined | null): Promise<ExtractResult>

/**
 * Options for a single extraction call. `pageType` overrides the classifier (and
 * suppresses `confidence`); `focus` tunes precision/recall; `url` feeds the cascade.
 */
export interface ExtractOptions {
  pageType?: 'article' | 'forum' | 'product' | 'collection' | 'listing' | 'documentation' | 'service'
  focus?: 'precision' | 'balanced' | 'recall'
  url?: string
}

/**
 * The extraction result. `contentHtml` is the preserve-markup output (script-free but
 * otherwise UNSANITIZED — the TS washing stage owns sanitization). `confidence` is
 * omitted when `pageType` was overridden.
 */
export interface ExtractResult {
  contentHtml: string
  pageType: 'article' | 'forum' | 'product' | 'collection' | 'listing' | 'documentation' | 'service'
  confidence?: number
  textLength: number
  fallbackUsed: boolean
  warnings: Array<string>
}

/**
 * Extract the main content of an HTML document synchronously (for scripting).
 *
 * # Errors
 * Throws a JS `Error` on an invalid `pageType`/`focus` string or if the classifier
 * artifacts fail to load.
 */
export declare function extractSync(html: string, options?: ExtractOptions | undefined | null): ExtractResult
